### ISSUE TITLE
Cannot update dependency in rekit on Windows

### ISSUE THREAD

**Issue by akoval** [rekit/rekit#205]
1) Created application using rekit cmd from scratch.
2) go to dependency list in studio
3) try to update anything

Result:

rekit is failed

```socket disconnected
running task:  npm update redux@latest --colors
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
npm ERR! code ELIFECYCLE
```

**Comment by sshahzaiib** [comment]
Same issue here with upgrading using yarn 

`Compiled successfully!

You can now view Rekit-react in the browser.     

  Local:            http://localhost:6075/       
  On Your Network:  http://192.168.56.1:6075/    

Note that the development build is not optimized.
To create a production build, use yarn build.    

To use Rekit Studio, access: http://localhost:6076

Error: ENOENT: no such file or directory, stat 'D:\Apps\Rekit-react\coverage\lcov-report\index.html'
running task:  yarn upgrade autoprefixer@latest --colors
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn yarn ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:262:19)
    at onErrorNT (internal/child_process.js:464:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at onErrorNT (internal/child_process.js:464:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn yarn',
  path: 'yarn',
Compiled successfully!

You can now view Rekit-react in the browser.      

  Local:            http://localhost:6075/        
  On Your Network:  http://192.168.56.1:6075/     

Note that the development build is not optimized. 
To create a production build, use yarn build.     

To use Rekit Studio, access: http://localhost:6076

running task:  yarn upgrade axios@latest --colors
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn yarn ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:262:19)
    at onErrorNT (internal/child_process.js:464:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:12)
    at onErrorNT (internal/child_process.js:464:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn yarn',
  path: 'yarn',
  spawnargs: [ 'upgrade', 'axios@latest', '--colors' ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS D:\Apps\Rekit-react>`
